# SPDX-FileCopyrightText: 2023 Anthony Loiseau <anthony.loiseau@allcircuits.com>
#
# SPDX-License-Identifier: LicenseRef-ALLCircuits-ACT-1.1

# Extend gitlab default stages list to prepend a "lint" stage
# so linters can quickly halt pipelines and avoid useless and
# maybe resources-ungry build,test,deploy stages.
stages:
  - lint
  - build
  - test
  - deploy

# Merge all our gitlab-ci.yml fragments.
# To uncomment when gitlab is updated
#include:
#  - local: '/gitlab-ci/**.gitlab-ci.yml'

# TODO: replace next lines with upper ones when gitlab is updated.
# - Our old gitlab does not support wildcards
# - Our old gitlab does not support multiple inclusions at once (list)
include:
  - local: '/gitlab-ci/reuse.gitlab-ci.yml'
